### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by TEZv** [TEZv/homepage#2]
### _Review_ and _update_ the content on the homepage to 
- [x] **provide accurate information** 

and 

- [x] **up-to-date information**. 

### **Labels:**
- [x] _Content_, _Frontend_

### **Milestones:**
- [x] more _time_ needed to _update_ the content with _appropriate_ information

**Assignees**: 
- [x] @TEZv

**Comment by TEZv** [comment]
Here's I Update the Homepage if needed

**Comment by TEZv** [comment]
2. Create a new branch named `feature/body` (based on develop), push it to origin - `git push -u origin feature/body`, and use it to edit main content:
    1. Preview index.html in a browser

    2. Create `patch/content/primary` (based on `feature/body`) branch.
    3. Add a primary content *(e.g. avatar, name, job, contacts, intro, etc.)* here. Commit small steps, add meaningful messages.
 
        - Contact info items example (should be place inside the contact-info__block)
        - Intro block (should be put below the previous container)

    4. Merge branch `patch/content/primary` into `feature/body` using pull request.
    5. Switch back to `feature/body` branch, pull changes using `git pull`.
    6. Create `patch/content/secondary` (based on `feature/body`) branch.
    7. Add a secondary content *(e.g. languages, skills, character, etc.)*. Commit small steps, add meaningful messages.
        - Skills block
          

        - Experiences block
            
        - Additional info

        
        As a preview, it should see something like this:
        
        - Preview
            
            !https://binary-studio-academy.github.io/stage-2/static/resume_template-8f3c289eb7670087b0825d1f0150e15b.png
            
    8. Merge branch `patch/content/secondary` into `feature/body` using pull request.
    9. Switch back to `feature/body` branch, pull changes using `git pull`.
    10. Iterate further and fill up the resume with **YOUR OWN** info - feel free to add new blocks, change structure, styles. Easter eggs are welcome too 😉
        

        
    11. Merge `feature/body` into `develop` using pull request.
   
3. Check if the HTML and CSS are valid. IT may may be used by [**[HTML validator](https://validator.w3.org/)**](https://validator.w3.org/) and [**[CSS validator](https://stylelint.io/demo)**](https://stylelint.io/demo) for this.

4. Open a pull request and **merge `develop` into `main`**.
