### ISSUE TITLE
Create a contact info block

### ISSUE THREAD

**Issue by TEZv** [TEZv/homepage#5]
### **Add a section with links to my:** 
- [x] social networks (LinkedIn, Facebook, Instagram), 
- [x] phone number,
- [x] email, 
- [x] Telegram username, or 
- [x] any other relevant contact information.

**Labels**: 
- [x] _Content, Frontend_

Assignees:
- [x] @TEZv 

**Milestones:** 
- [ ] Initial Development
> create info block with _semantics_ and add info with _1 hour to do_

**Comment by TEZv** [comment]
This needs to include **_my links and contacts._**
