### ISSUE TITLE
Create additional info blocks

### ISSUE THREAD

**Issue by TEZv** [TEZv/homepage#7]
### I can make my resume less official by adding _more_: 
**_entertaining info, like_**: 
- [x] my hobbies and 
- [x] my interest, or 
- [x] what do you like, 
- [x] some interactive content or joke
- [x] easter egg

**Labels**: 
- [x] _Content, Frontend_

Assignees:
- [x] @TEZv 

**Milestones:** 
- [x] Content
> create info block with _semantics_ and add info with _2 hours to do_

**Comment by TEZv** [comment]
It is all about how I _**rest**_ while not working,
IS also **_IMPORTANT_**
And take **2 hours** to do
